name: Root Workflow (Passing JSON)

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/passing-json.yml"
      - ".github/workflows/using-json.yml"

jobs:
  static:
    outputs:
      runners:
        - runner: ubuntu-latest
          groups: [x, y]
        - runner: linux-arm64
          groups: [x]
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: |
          echo Do nothing

  job:
    needs: [static]
    strategy:
      fail-fast: false
      matrix:
        group: [x, y]
    name: Group ${{ matrix.group }}
    uses: ./.github/workflows/using-json.yml
    with:
      runner: ${{ toJSON(needs.static.outputs.runners) }}
      group: ${{ matrix.group }}
